language: node_js
sudo: false
branches:
  except:
    - develop
script: npm run cover
node_js:
  - '4.1'
  - '4.0'
  - '0.12'
  - stable
after_success:
  - npm run coveralls
deploy:
  provider: npm
  email: freeformsystems@gmail.com
  api_key:
    secure: lPp4luw1OAlZt6tRdT0cqxeKdEFZJvUb2daKw20AQj4QMsKxSEFW2MEBjU7lpgB4SVVBi9nU05uKIa86CnLkEFQja2L4bndqudbRCbNAsVsVbSkFp1aH5HOtLTDygxsnfFHGZRNmcubeX2h4owKkH78mEoRo4/54MzXC0Zfrs9her1xLRBD75lk74QLKnf2jac4AaCQFFsYb8G6KEHpKy9071e6mKpzdYhfwaeusXjc2Pan8Q++TEbry7SHgJ5XRs2IpWHjxNpzvfNlXt2Qq3AmQ/RE0KwQINAZuvoc2ymNLjo66kk0mrOFiP4YM1hyw7kluNBfF8tt/P6ULJL/XArfeDq6Q/fAMC+cvJEws610aDTxgNAF8oa0niH3E2c8XKnqDTgV1nBL2oAiJP48HKZajRa9nHejYmPZosQv54AH/F0mfl/lUAeHPaHxBluX1NGgMIteHqoxeYwV8t+PRJtaMONUaKaf3rdrmOTIoEWemv7aUZqHxeHMJyXv5PqqIT9HKkgzDCXFC4jM7Kb9Q3fdquBpL7mUnA7KOGQgi0zHIUkPjHCmkJo44QZ44fm1lEN9T1fyDNRMJ0xElpMZnQm33efqsvHxaLfc7AikH0wEkboU94mS7W7q2iL0dZuz72AS/3RCXhpoydjYLHiS1nnmeSWtZpbeaFCsjitNA8xE=
  on:
    tags: true
    repo: mkdoc/mktask
    node: '4.1'
